<?php

namespace App\Services\Subdomain;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Validation\Rule;

class CloudflareService
{
    function checkStatus(object $cloudRequest, bool $id) {
        $status = $cloudRequest->status();
        if ($status >= 400 && $status <= 499) {
            $jsonData = $cloudRequest->json();
            $response = Http::post('https://haste.bagou450.com/documents', $jsonData);
            if ($response->successful()) {
                return response()->json([
                    'status' => 'error',
                    'message' => 'CloudFlare API returned an error. Request was malformed.',
                    'data' => $response->header('X-Document-URL')
                ]);
            } else {
                return response()->json([
                    'status' => 'error',
                    'message' => 'CloudFlare API returned an error. Request was malformed.',
                    'data' => 'https://haste.bagou450.com'
                ]);
            }

        } else {
            $answer = [
                'status' => 'success',
                'message' => 'The operation on the record was made successfully.',

            ];
            if($id) {
                $answer['id'] = $cloudRequest->json()['result']['id'];
            }
            return response()->json($answer);
        }
    }

    public function create(Request $request) {
        $validated = $request->validate([
            'key' => 'required',
            'domain' => 'required',
            'record' => 'required',
            'recordType' => [
                'required',
                Rule::in(['A', 'AAAA','CNAME','SRV']),
            ],
            'value' => 'required',
            'ttl' =>  [
                'required',
                'integer',
                'between:600,86400',
            ],
            'port' => [
                'nullable',
                'integer',
                'numeric',
                'between:1,65535',
            ],
            'protocol' => [
                'nullable',
                Rule::in(['TCP','tcp','udp', 'UDP']),
            ],
            'priority' => 'nullable|integer',
            'weight' => 'nullable|integer|between:0,65535',
            'service' => 'nullable|string'
        ]);

        $domain = $validated['domain'];
        $type = $validated['recordType'];
        $key = $validated['key'];

        if($type === 'SRV' && ((!isset($validated['port']) || !$validated['port']) || !isset($validated['priority']) || (!isset($request['protocol']) || !$request['protocol']) || (!isset($validated['service']) || !$validated['service']) || !isset($validated['weight']))) {
            return response()->json([
                'status' => 'error',
                'message' => 'Some data are missing for make a SRV record (In Port,Priority,Protocol,Service,Weight).'
            ]);
        }
        $putData = [
            'content' => $validated['value'],
            'ttl' => intval($validated['ttl']),
            'name' => $validated['record'],
            'proxied' => false,
            'type' => $validated['recordType'],
            'comment' => 'Generated by Bagou450 Subdomain module.',
            'tag' => ["bagou450","pterodactyl"],
        ];
        if($type == 'SRV') {
            $putData['content'] = $validated['priority'] . ' ' . $validated['weight'] . ' ' . $validated['port'] . ' ' . $validated['value'];
            $putData['name'] =  $validated['service'] . '._' . $validated['protocol'] . '. '. $validated['value'];
            $putData = $putData + [
                    'data' => [
                        'priority' => intval($validated['priority']),
                        'weight' => intval($validated['weight']),
                        'port' => intval($validated['port']),
                        'target' => $validated['value'],
                        'service' => $validated['service'],
                        'proto' => '_' . $validated['protocol'],
                        'name' => $validated['record'],
                    ]
            ];
        }
        $cloudRequest = Http::withHeaders([
            'Authorization' => "Bearer $key"
        ])->post("https://api.cloudflare.com/client/v4/zones/$domain/dns_records", $putData);
        return $this->checkStatus($cloudRequest, true);
    }
    public function delete(Request $request) {
        $validated = $request->validate([
            'key' => 'required',
            'domain' => 'required',
            'record' => 'required',
            'recordType' => [
                'required',
                Rule::in(['A', 'AAAA','CNAME','SRV']),
            ]
        ]);
        $domain = $validated['domain'];
        $record = $validated['record'];
        $key = $validated['key'];
        $cloudRequest = Http::withHeaders([
            'Authorization' => "Bearer $key"
        ])->delete("https://api.cloudflare.com/client/v4/zones/$domain/dns_records/$record");
        return $this->checkStatus($cloudRequest, false);
    }

}